/**
 * Copyright (c) 2011 Roger Myrg http://devshop.me/
 * Released under the MIT license:
 * https://github.com/rgr-myrg/DevShop-JS/raw/master/MIT-LICENSE
 */
(function(){window.DevShop=typeof window.DevShop==="object"?window.DevShop:{};window.DevShop.Me=function(c){for(var b in c)c.hasOwnProperty(b)&&(window.DevShop[b]=c[b])}})();(function(){DevShop.Me({SingletonFactory:function(c){var b=function(a){if(typeof a==="function")try{return new a}catch(d){}else if(typeof a==="object")return a},e=b(c.implement),a=b(c.extend),b=b(c.instance),d;for(d in a)a.hasOwnProperty(d)&&(b[d]||(b[d]=a[d]));for(d in e)if(e.hasOwnProperty(d)&&!b[d])throw c.instance+" must implement '"+d+"' "+typeof e[d];if(typeof b.initialize==="function")try{b.initialize()}catch(h){}return b}})})();(function(){DevShop.Me({Observable:function(c){return DevShop.SingletonFactory({extend:function(){this.observers=[];this.addObserver=function(b){if((typeof b==="function"||typeof b==="object")&&typeof b.notify==="function")if(this.observers.push(b),typeof b.onRegister==="function")try{b.onRegister()}catch(c){}};this.notifyObservers=function(b){for(var c=this.observers.length,a=0;a<c;a++)try{this.observers[a].notify(b,this)}catch(d){}}},instance:c})}})})();(function(){DevShop.Me({Observer:function(c){return DevShop.SingletonFactory({extend:function(){this.onRegister=function(){};this.notify=function(b,c){this.observable=c;if(typeof this[b]==="function")try{this[b]()}catch(a){}}},instance:c})}})})();(function(){DevShop.Me({EventSignal:function(){var c=[];this.addListener=function(b){typeof b==="function"&&c.push(b)};this.removeListener=function(b){for(var e=c.length,a=0;a<e;a++)c[a]===b&&c.splice(a)};this.dispatch=function(){for(var b=c.length,e=0;e<b;e++)try{c[e].apply(this,arguments)}catch(a){}}}})})();(function(){DevShop.Me({IProxy:{NAME:""},IMediator:{NAME:"",listNotificationInterests:function(){},handleNotification:function(){}},ICommand:{execute:function(){}},Proxy:function(){var c={};this.facade=null;this.setData=function(b){c=b};this.getData=function(){return c};this.onRegister=function(){};this.onRemove=function(){}},Mediator:DevShop.Observer(function(){this.facade=null;this.onRegister=function(){};this.onRemove=function(){}}),Facade:function(){var c=new function(){var a={};this.facade={};
this.registerProxy=function(d){d.facade=this.facade;a[d.NAME]||(a[d.NAME]=d);if(typeof d.onRegister==="function")try{d.onRegister()}catch(b){}};this.retrieveProxy=function(d){return a[d]?a[d]:null};this.removeProxy=function(d){if(typeof a[d].onRemove==="function")try{a[d].onRemove()}catch(b){}a[d]=null}},b=new DevShop.Observable(function(){var a={};this.facade={};this.notification={};this.registerMediator=function(d){d.facade=this.facade;a[d.NAME]||(a[d.NAME]=d,this.addObserver(d))};this.retrieveMediator=
function(d){return a[d]?a[d]:null};this.removeMediator=function(d){if(typeof a[d].onRemove==="function")try{a[d].onRemove()}catch(b){}a[d]=null};this.notifyObservers=function(a){for(var b=this.observers.length,c=0;c<b;c++)try{for(var e=this.observers[c].listNotificationInterests(),g=!1,f=0;l=e.length,f<l;f++)if(e[f]==this.notification.name){g=!0;break}if(g)this.observers[c].notification=this.notification,this.observers[c].notify(a,this)}catch(i){}};this.sendNotification=function(a){this.notification=
a;this.notifyObservers("handleNotification")}}),e=new DevShop.Observer(function(){var a={},b=[];this.facade={};this.NAME="DevShop.Controller";this.registerCommand=function(c,e){e.facade=this.facade;a[c]||(a[c]=e,b.push(c))};this.listNotificationInterests=function(){return b};this.handleNotification=function(){var b=this.notification;if(typeof a[b.name]==="object"&&typeof a[b.name].execute==="function")try{a[b.name].execute(b)}catch(d){}}});this.CMD_STARTUP="CMD_STARTUP";this.registerProxy=function(a){c.registerProxy(a)};
this.registerMediator=function(a){b.registerMediator(a)};this.registerCommand=function(a,b){e.registerCommand(a,b)};this.retrieveProxy=function(a){return c.retrieveProxy(a)};this.retrieveMediator=function(a){return b.retrieveMediator(a)};this.removeProxy=function(a){c.removeProxy(a)};this.removeMediator=function(a){b.removeMediator(a)};this.sendNotification=function(a,c,e){b.sendNotification({name:a,body:c,type:e})};this.initializeFacade=function(){c.facade=this;b.facade=this;e.facade=this;this.registerMediator(e)}}})})();
