/**
 * Copyright (c) 2011 Roger Myrg http://devshop.me/
 * Released under the MIT license:
 * https://github.com/rgr-myrg/DevShop-JS/raw/master/MIT-LICENSE
 */
(function(b){b.DevShop=typeof b.DevShop==="object"?b.DevShop:{}})(window);(function(b){b.SingletonFactory=function(b){var c=function(a){if(typeof a==="function")try{return new a}catch(d){}else if(typeof a==="object")return a},e=c(b.implement),a=c(b.extend),c=c(b.instance),d;for(d in a)a.hasOwnProperty(d)&&(c[d]||(c[d]=a[d]));for(d in e)if(e.hasOwnProperty(d)&&!c[d])throw b.instance+" must implement '"+d+"' "+typeof e[d];if(typeof c.initialize==="function")try{c.initialize()}catch(h){}return c}})(DevShop);(function(b){b.Observable=function(f){return b.SingletonFactory({extend:function(){this.observers=[];this.addObserver=function(c){if((typeof c==="function"||typeof c==="object")&&typeof c.notify==="function")if(this.observers.push(c),typeof c.onRegister==="function")try{c.onRegister()}catch(b){}};this.notifyObservers=function(c){for(var b=this.observers.length,a=0;a<b;a++)try{this.observers[a].notify(c,this)}catch(d){}}},instance:f})}})(DevShop);(function(b){b.Observer=function(f){return b.SingletonFactory({extend:function(){this.onRegister=function(){};this.notify=function(c,b){this.observable=b;if(typeof this[c]==="function")try{this[c]()}catch(a){}}},instance:f})}})(DevShop);(function(b){b.EventSignal=function(){var b=[];this.addListener=function(c){typeof c==="function"&&b.push(c)};this.removeListener=function(c){for(var e=b.length,a=0;a<e;a++)b[a]===c&&b.splice(a)};this.dispatch=function(){for(var c=b.length,e=0;e<c;e++)try{b[e].apply(this,arguments)}catch(a){}}}})(DevShop);(function(b){b.IProxy={NAME:""};b.IMediator={NAME:"",listNotificationInterests:function(){},handleNotification:function(){}};b.ICommand={execute:function(){}};b.Proxy=function(){var b={};this.facade=null;this.setData=function(c){b=c};this.getData=function(){return b};this.onRegister=function(){};this.onRemove=function(){}};b.Mediator=b.Observer(function(){this.facade=null;this.onRegister=function(){};this.onRemove=function(){}});b.Facade=function(){var f=new function(){var a={};this.facade={};this.registerProxy=
function(d){d.facade=this.facade;a[d.NAME]||(a[d.NAME]=d);if(typeof d.onRegister==="function")try{d.onRegister()}catch(b){}};this.retrieveProxy=function(d){return a[d]?a[d]:null};this.removeProxy=function(d){if(typeof a[d].onRemove==="function")try{a[d].onRemove()}catch(b){}a[d]=null}},c=new b.Observable(function(){var a={};this.facade={};this.notification={};this.registerMediator=function(d){d.facade=this.facade;a[d.NAME]||(a[d.NAME]=d,this.addObserver(d))};this.retrieveMediator=function(d){return a[d]?
a[d]:null};this.removeMediator=function(d){if(typeof a[d].onRemove==="function")try{a[d].onRemove()}catch(b){}a[d]=null};this.notifyObservers=function(a){for(var b=this.observers.length,c=0;c<b;c++)try{for(var e=this.observers[c].listNotificationInterests(),f=!1,g=0;l=e.length,g<l;g++)if(e[g]==this.notification.name){f=!0;break}if(f)this.observers[c].notification=this.notification,this.observers[c].notify(a,this)}catch(i){}};this.sendNotification=function(a){this.notification=a;this.notifyObservers("handleNotification")}}),
e=new b.Observer(function(){var a={},b=[];this.facade={};this.NAME="DevShop.Controller";this.registerCommand=function(c,e){e.facade=this.facade;a[c]||(a[c]=e,b.push(c))};this.listNotificationInterests=function(){return b};this.handleNotification=function(){var b=this.notification;if(typeof a[b.name]==="object"&&typeof a[b.name].execute==="function")try{a[b.name].execute(b)}catch(c){}}});this.CMD_STARTUP="CMD_STARTUP";this.registerProxy=function(a){f.registerProxy(a)};this.registerMediator=function(a){c.registerMediator(a)};
this.registerCommand=function(a,b){e.registerCommand(a,b)};this.retrieveProxy=function(a){return f.retrieveProxy(a)};this.retrieveMediator=function(a){return c.retrieveMediator(a)};this.removeProxy=function(a){f.removeProxy(a)};this.removeMediator=function(a){c.removeMediator(a)};this.sendNotification=function(a,b,e){c.sendNotification({name:a,body:b,type:e})};this.initializeFacade=function(){f.facade=this;c.facade=this;e.facade=this;this.registerMediator(e)}}})(DevShop);
