/**
 * Copyright (c) 2011 DevShop http://devshop.me/
 * Version: {version}
 * Released under the MIT license:
 * https://github.com/rgr-myrg/DevShop-JS/raw/master/MIT-LICENSE
 */
(function(b){b.DevShop=typeof b.DevShop==="object"?b.DevShop:{}})(window);(function(b){b.SingletonFactory=function(d){var a=function(c){if(typeof c==="function")try{return new c}catch(a){}else if(typeof c==="object")return c},b=a(d.__implement),c=a(d.__extend),a=a(d.__construct),f;for(f in c)c.hasOwnProperty(f)&&(a[f]||(a[f]=c[f]));for(f in b)if(b.hasOwnProperty(f)&&!a[f])throw d.instance+" must implement '"+f+"' "+typeof b[f];if(typeof a.initialize==="function")try{a.initialize()}catch(i){}return a}})(DevShop);(function(b){b.Observable=function(d){return b.SingletonFactory({__extend:function(){return{observers:[],addObserver:function(a){if((typeof a==="function"||typeof a==="object")&&typeof a.notify==="function")if(this.observers.push(a),typeof a.onRegister==="function")a.onRegister()},notifyObservers:function(a){for(var b=this.observers.length,c=0;c<b;c++)this.observers[c].notify(a,this)}}},__construct:d})}})(DevShop);(function(b){b.Observer=function(d){return b.SingletonFactory({__extend:function(){return{onRegister:function(){},notify:function(a,b){this.observable=b;if(typeof this[a]==="function")try{this[a]()}catch(c){}}}},__construct:d})}})(DevShop);(function(b){b.EventSignal=function(){var b=[];return{addListener:function(a){typeof a==="function"&&b.push(a)},removeListener:function(a){for(var e=b.length,c=0;c<e;c++)b[c]===a&&(b[c]=null)},dispatch:function(){for(var a=[],e=b.length,c=0;c<e;c++)typeof b[c]==="function"?b[c].apply(this,arguments):a.push(c);e=a.length;for(c=0;c<e;c++)b.splice(c,1)}}}})(DevShop);(function(b){b.IProxy={NAME:""};b.IMediator={NAME:"",listNotificationInterests:function(){},handleNotification:function(){}};b.ICommand={execute:function(){}};b.Proxy=function(){var b={};return{facade:null,setData:function(a){b=a},getData:function(){return b},onRegister:function(){},onRemove:function(){}}};b.Mediator=b.Observer(function(){return{facade:null,onRegister:function(){},onRemove:function(){}}});b.Facade=function(){var d=function(){var c={};return{facade:{},registerProxy:function(a){a.facade=
this.facade;c[a.NAME]||(c[a.NAME]=a);if(typeof a.onRegister==="function")a.onRegister()},retrieveProxy:function(a){return c[a]?c[a]:null},removeProxy:function(a){if(typeof c[a].onRemove==="function")c[a].onRemove();c[a]=null}}}(),a=new b.Observable(function(){var c={};return{facade:{},notification:{},registerMediator:function(a){a.facade=this.facade;c[a.NAME]||(c[a.NAME]=a,this.addObserver(a))},retrieveMediator:function(a){return c[a]?c[a]:null},removeMediator:function(a){if(typeof c[a].onRemove===
"function")c[a].onRemove();c[a]=null},notifyObservers:function(a){for(var c=this.observers.length,b=0;b<c;b++){for(var d=this.observers[b].listNotificationInterests(),e=!1,g=0,h=d.length;g<h;g++)if(d[g]==this.notification.name){e=!0;break}if(e)this.observers[b].notification=this.notification,this.observers[b].notify(a,this)}},sendNotification:function(a){this.notification=a;this.notifyObservers("handleNotification")}}}),e=new b.Observer(function(){var a={},b=[];return{facade:{},NAME:"BTG.Controller",
registerCommand:function(d,e){e.facade=this.facade;a[d]||(a[d]=e,b.push(d))},listNotificationInterests:function(){return b},handleNotification:function(){var b=this.notification;typeof a[b.name]==="object"&&typeof a[b.name].execute==="function"&&a[b.name].execute(b)}}});return{CMD_STARTUP:"CMD_STARTUP",registerProxy:function(a){d.registerProxy(a)},registerMediator:function(c){a.registerMediator(c)},registerCommand:function(a,b){e.registerCommand(a,b)},retrieveProxy:function(a){return d.retrieveProxy(a)},
retrieveMediator:function(c){return a.retrieveMediator(c)},removeProxy:function(a){d.removeProxy(a)},removeMediator:function(b){a.removeMediator(b)},sendNotification:function(b,d,e){a.sendNotification({name:b,body:d,type:e})},initializeFacade:function(){d.facade=this;a.facade=this;e.facade=this;this.registerMediator(e)}}}})(DevShop);(function(b){b.Publisher=function(){var b={};return{registerEvents:function(a){typeof a==="object"&&(b=a)},registerSubscriber:function(a){if(typeof a.onRegister==="function"){var e=a.onRegister(),c;for(c in e)e.hasOwnProperty(c)&&typeof b[c]==="object"&&b[c].addListener(e[c]);a.onRegister=function(){}}},notify:function(a,b){typeof a.dispatch==="function"&&a.dispatch(b)}}}})(DevShop);
